#!/bin/sh

DB_DRIVER='django_orm.backends.mysql'
DB_NAME=${DB_NAME:-django_mysql_test}
DB_USER=${DB_USER:-root}

echo "DROP DATABASE IF EXISTS $DB_NAME " | mysql -u $DB_USER
echo "CREATE DATABASE  $DB_NAME" | mysql -u $DB_USER
DB_NAME=$DB_NAME DB_USER=$DB_USER DB_DRIVER=$DB_DRIVER python2 tests/run.py "$@"
